my_list= []

fruits= ["apple", "banana", "cherry"]

numbers= [1,2,3,4,5]

mixlist= [1,"apple",True, 2.5]

print("Fruits:", fruits)
print("Numbers:", numbers)
print("mixed list:", mixlist)


print("elemen pertama fruits" , fruits[0])
print("elemen terakhir numbers" , numbers[-1])

fruits.append("orange")
print("fruits setelah di append", fruits )

numbers[0]= 10
print("numbers setelah diubah dengan menambah elemen pada indeks pertama", numbers)

